name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Assemble

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: bash ./gradlew build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Run Lint
      run: bash ./gradlew lintDebug
    - name: Upload Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html
        if-no-files-found: ignore
  
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Unit Tests
      run: bash ./gradlew test
    - name: Upload Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: app/build/reports/tests/testDebugUnitTest/
        if-no-files-found: ignore
